DROP TABLE "ARTIST";
CREATE TABLE "ARTIST" (
  "aID" NUMBER NOT NULL,
  "Name" VARCHAR2(30) NOT NULL,
  "Gender" VARCHAR2(20) NOT NULL,
  "Birth_Date" DATE NOT NULL,
  "Nationality" VARCHAR2(30) NOT NULL,
  "Birth_Place" VARCHAR2(30) NOT NULL,
  "Death_Date" DATE,
  "Photo" BLOB,
  CONSTRAINT "ArtistPK" PRIMARY KEY ("aID")
);

CREATE SEQUENCE seq_artist
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

