DROP TABLE "SHOW_GENRE";
CREATE TABLE "SHOW_GENRE" (
  "sID" NUMBER NOT NULL,
  "gID" NUMBER NOT NULL,
  CONSTRAINT "ShowGenrePk" PRIMARY KEY ("sID", "gID")
);

ALTER TABLE "Show_Genre" ADD CONSTRAINT "Show_Show_Genre_Fk" FOREIGN KEY ("sID") REFERENCES Show("sID") ON DELETE CASCADE;
ALTER TABLE "Show_Genre" ADD CONSTRAINT "Genre_Show_Genre_Fk" FOREIGN KEY ("gID") REFERENCES Genre("gID") ON DELETE CASCADE;
