DROP TABLE "USERS";
CREATE TABLE "USERS" (
  "usID" NUMBER NOT NULL,
  "User_Name" VARCHAR2(30) NOT NULL,
  "Password" VARCHAR2(30) NOT NULL,
  CONSTRAINT "UserPk" PRIMARY KEY ("usID"),
  CONSTRAINT "UserName" UNIQUE ("User_Name")
);

CREATE SEQUENCE seq_users
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;
